### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function oci_connect() in /var/www/html/ocitest.php:3 Stack trace: #0 {main} thrown in /var/www/html/ocitest.php on line 3

### ISSUE THREAD

**Issue by flik** [adrianharabula/php-oci8#7]
php file:

```
<?php

$conn = oci_connect('system', 'oracle', 'oracledb/XE');
if (!$conn) {
    $e = oci_error();
    trigger_error(htmlentities($e['message'], ENT_QUOTES), E_USER_ERROR);
} else echo 'succesful';
``` 

here is docker-compose.yml:

```
version: '3'

services:
   oracledb:
     image: wnameless/oracle-xe-11g
     ports:
      - "1521:1521"

   php7-with-oci8:
     depends_on:
       - oracledb
     image: adrianharabula/php7-with-oci8
     build:
        context: .
        dockerfile: ./php72/Dockerfile
     volumes:
      - ./www:/var/www/html
     ports:
      - "8181:80"

```
